src/snippets/C++/bellman-ford.tsx
I have added bellman-ford algorithm in c++. i have also added its us case , reference and how to use.
=> Fixed issue number #18

src/snippets/C++/Algorithm/binarysearch.tsx
Binary Search Algorithm in java, python and C++
=> Binary Search Algorithm in java, python and C++

src/snippets/C++/Algorithm/depthfirstsearch.tsx
In this PR, I have added the DFS algorithm code in C++, Java, and Python, maintaining the same UI as the other pages.
=> Added Dfs algorithm file  issue no  #14 

src/snippets/C++/Algorithm/AStar.tsx
=> implemented A* path finding algorithm

src/App.tsx, src/snippets/C++/MergeSort.tsx
=> Added Merge Sort Snippet for C++

src/App.tsx, src/dashboard.tsx, src/snippets/web/XMLHttpRequest.tsx, src/snippets/web/axios.tsx, src/snippets/web/fetchAPI.tsx
Hi there,i have made all the changes and work you assigned ,please review it after then, please let me know.
=> Addeda JavaScript Snippets.  #8

src/App.tsx, src/dashboard.tsx, src/snippets/Algorithm/DijkstraAlgorithm.tsx, src/snippets/C++/heapSort.tsx
hey i added dijkstra's algorithm snippet in Algorithm and heapsort snippet in c++ can please merge it!
=> added dijkstra's algorithm and heapsort

src/App.tsx, src/dashboard.tsx, src/snippets/Java/ThreadSynchronizationJava.tsx
I created ThreadSynchronization snipped in java
=> ThreadSynchronization added

src/App.tsx, src/dashboard.tsx, src/snippets/javascript/WebSocket.tsx
Added client-side WebSocket implementation that connects to the server, sends messages, and handles incoming messages.
Developed server-side WebSocket logic to handle client connections, send welcome messages, and respond to client messages.
https://github.com/user-attachments/assets/cd3495eb-62d1-4de2-9d80-5dd5bac05488
=> feat: WebSocket implementation in JavaScript (#21)

src/App.tsx, src/dashboard.tsx, src/snippets/C++/BreadthFirstSearch.tsx
Fixes:#52
Added BFS card on the main page as below 
also added corresponding router
=> Added BFS code snippet in C++

src/App.tsx, src/snippets/palindromeChecker/palindrome.tsx
I have added palindrome checker code in different languages , Kindly review it and tell me.
=> Added palindromChecker #6

package-lock.json, package.json, src/App.tsx, src/dashboard.tsx, src/snippets/Algorithm/BlowfishCipher.tsx
Addes Use Case and How to use for Blowfish Cipher Algorithm.
As per the issue, also made two fields(one for the key and other one for the message) for the input from the user to encrypt/decrypt the message.
=> Added Documentation and Implementation for Blowfish Cipher (Issue #49)

src/App.tsx, src/dashboard.tsx, src/snippets/Python/Listcomprehension.tsx
✅ Closes: #3
This pull request introduces a new feature for showcasing list comprehensions in Python within the application. The most important changes include adding a new component for list comprehension, updating various routes to include the new feature, and modifying the dashboard to display the new card for list comprehension.
New feature addition:
* [`src/snippets/Python/Listcomprehension.tsx`](diffhunk://#diff-436bef101cc7b793e7fde9cb42b011dc757751597bcbde7a9121880837267730R1-R227): Added a new component `ListComprehension` that includes detailed Python code snippets demonstrating various ways to use list comprehension for filtering, transforming, and more complex operations.
Route updates:
* [`src/App.tsx`](diffhunk://#diff-26ad4b834941d9b19ebf9db8082bd202aaf72ea0ddea85f5a8a0cb3c7 …
=> fix: 🐛 Add Python Code snippet: List comprehension

src/App.tsx, src/dashboard.tsx, src/snippets/Python/Web-scraper.tsx
✅ Fixes: #7 
This PR introduces a new web scraper feature to the application. The main changes include the addition of a new `WebScraper` component, updates to the routing and dashboard to include this new feature, and the integration of a code snippet demonstrating how to perform web scraping in Python.
* **New Component: `WebScraper`**
- Added a new file `src/snippets/Python/Web-scraper.tsx` containing the `WebScraper` component, which includes a Python code snippet for web scraping using `requests` and `BeautifulSoup`.
* **Route Addition**
- Added a new route for the `WebScraper` component in `src/App.tsx` to make it accessible via `/Web-scraper`.
* **Dashboard Card**
- Updated the `Dashboard` component in `src/dashboard.tsx` to include a card for the `Web Scraper` feature, allowing …
=> Feat: Add Web Scrape python code-snippet using BeautifulSoup (bs4) 

src/App.tsx, src/dashboard.tsx, src/snippets/Ciphers/CaeserCipher.tsx
=> Caeser Cipher program is added

src/App.tsx, src/components/card.tsx, src/dashboard.tsx
Fixes: #75,  
Fixes: #77 
Implemented responsive design for the dashboard ensuring optimal display across devices and truncated long titles exceeding 25 words and removed an unnecessary route and card from the dashboard page.
=> Fix/threadsynchronizationjava route and responsive dashboard  #75

src/App.tsx, src/components/Navbar.tsx, src/dashboard.tsx
Fixes: #79
Implemented Search functionality.
=> feat: Search functionality #79

src/App.tsx, src/dashboard.tsx, src/snippets/javascript/OAuth2_Authorization.tsx
Fixes: #15 
Added the implementation of the OAuth2 Authorization Code Flow using Passport.js with Google.
=> feat: OAuth2 Authorization code flow

src/App.tsx, src/dashboard.tsx, src/snippets/Ciphers/ChaCha20-cipher.tsx
Fixes: #67 implimented
Please assign the issue to me and merge this PR
=> added ChaCha20-cipher #67

package-lock.json, package.json, src/App.tsx, src/components/codeSnippet.tsx, src/dashboard.tsx, src/snippets/Algorithm/AES.tsx, src/snippets/Algorithm/SHA3Hash.tsx, src/snippets/Ciphers/VigenereCipher.tsx
Fixed: #41 
This pull request includes the following updates:
1. **Vigenère Cipher Component**:
- Created the main `VigenereCipher.tsx` file, implementing a fully functional Vigenère Cipher encryption and decryption feature.
- Allows users to input a message and a key to either encrypt or decrypt the text.
- Implemented input validation to ensure both text and key are provided before processing.
- Used React's `useState` hook to manage text, key, and output states.
- Added an interactive UI with Tailwind CSS, including buttons to toggle between encryption and decryption modes.
2. **CodeSnippet Component**:
- Updated the `CodeSnippet.tsx` file to handle code block rendering for various languages with copy-to-clipboard functionality.
- Syntax highlighting using `react-syntax-highlighter` …
=> Updated code for Vigenère Cipher issue no #41

src/snippets/Algorithm/SHA3Hash.tsx
Fixes: #66
Fixes: #46
This PR addresses the following issues:
- **SHA-3 Hash Function Implementation (#66)**: Implemented a SHA-3 (Keccak) hash generator component in the React project using the `js-sha3` library, allowing users to input data and generate a cryptographic hash.
- **AES Encryption/Decryption Support (#46)**: Added AES (Advanced Encryption Standard) functionality, enabling encryption and decryption of text data using a secret key. This feature supports AES-128, AES-192, and AES-256 modes.
- **Problem**: The project required a secure cryptographic hash function to hash arbitrary user inputs using SHA-3, the latest standard developed by NIST.
- **Solution**: Introduced the `SHA3Hash` component, leveraging the `js-sha3` library. The component:
- Accepts user input via a text …
=> SHA-3 (Secure Hash Algorithm 3) and Advanced Encryption Standard (AES) issue number #66 and #46

src/App.tsx, src/dashboard.tsx, src/snippets/Ciphers/PlayfairCipher.tsx
=> Play cipher Implemented

package-lock.json, package.json, src/App.tsx, src/components/Footer.tsx, src/components/Slider.tsx, src/index.css, tailwind.config.js
=> [FEATURE] added footer #85

src/App.tsx, src/dashboard.tsx, src/snippets/Ciphers/VernamCipher.tsx
=> Added Vernam Cipher

src/App.tsx, src/dashboard.tsx
fixes: #97 and a typo in binary search
=> Refactoring App.tsx done 

src/App.tsx, src/dashboard.tsx, src/snippets/Ciphers/DiffieHellman.tsx
=> added diffiehellman algo  

src/App.tsx, src/dashboard.tsx, src/snippets/Ciphers/DiffieHellman.tsx, src/snippets/Ciphers/ellipticCurve.tsx
=> elliptic cipher
